---
title: "DA_Project"
author: "Nina"
date: "4/20/2022"
output: html_document
---

```{r, echo = FALSE, message = FALSE}
source(here::here("Scripts/SetUp.R"))
```

### EDA


# Response attribute transformation
 
```{r }
n <- dim(bands3_reduced)[1]
p <- dim(bands3_reduced)[2]
```
n = ROW = 540 observartions 
p = COLUMN = 29 variables/characteristics

## Data structure and summary
 
```{r }
str(bands3_reduced)
head(bands3_reduced)
summary(bands3_reduced)
describe(bands3_reduced)
as_tibble(bands3_reduced)
datatable(bands3_reduced)
```

```{r }
dfSummary(bands3_reduced, style = "grid")
```

# DataExpolrer library

```{r }
introduce(bands3_reduced[,-29])
plot_intro(bands3_reduced[,-29])
```

# Missing observations
```{r }
nrows <- nrow(bands3_reduced)
n.missing <- rowSums(is.na(bands3_reduced))
sum(n.missing > 0)/nrows
```

```{r }
n.complete <- sum(complete.cases(bands3_reduced))
n.complete/nrows
```

```{r }
plot_missing(bands3_reduced[,-30])
```

# 1. We plot the numerical variables: 
```{r }
plot_histogram(bands3_reduced[,-29]) #Histogram

plot_density(bands3[,-30],
             ggtheme = theme_bw()) # Density plots

plot_boxplot(bands3_reduced, by = '',  ncol = 2,
             title = "Side-by-side boxplots") # Boxplot
```

# 2. We plot the categorical variables: 
```{r}
bands3_reduced %>%
  keep(is.factor) %>%
  gather() %>%
  ggplot(aes(value)) +
  facet_wrap(~ key, scales = "free") +
  geom_bar(stat="count") +
  coord_flip()
```

```{r}
ggplot(bands3_reduced) +
  geom_bar(aes(x = Mountain_range))
```
























# d. Side-by-side boxplots
???

# e. Variables summaries 
???
```{r }
quanti<-1:30
mat<-matrix(0, length(quanti), 7)
colnames(mat)<-c("Min.", "1st Qu.", "Median", "Mean", "Sd", "3rd Qu.", "Max.")
rownames(mat)<-names(bands3_reduced)[quanti]
mat[,1]<-apply(bands3_reduced[,quanti], 2, min)
mat[,2]<-apply(bands3_reduced[,quanti], 2, quantile, 0.25)
mat[,3]<-apply(bands3_reduced[,quanti], 2, median)
mat[,4]<-apply(bands3_reduced[,quanti], 2, mean)
mat[,5]<-apply(bands3_reduced[,quanti], 2, sd)
mat[,6]<-apply(bands3_reduced[,quanti], 2, quantile, 0.75)
mat[,7]<-apply(bands3_reduced[,quanti], 2, max)
print(round(mat, 2))
```

# f. Pairwise comparison
```{r }
bands3.quant <- bands3[,quanti]
plot_correlation(bands3.quant, type = 'c', cor_args = list('use'='complete.obs'))
pairs(bands3.quant)
```
???
```{r }
pairs.panels(bands3.quant)
ggpairs(bands3)
```
???
```{r }
ggpairs(bands3[,-39], ggplot2::aes())
```
???
```{r }
cor(bands3.quant)
```
???
```{r }
corrplot(cor(bands3.quant))
```
???
```{r }
d<-correlate(bands3.quant)         
d %>%
+   shave() %>% # Remove the upper triangle
+   fashion()
```
???
```{r }
d %>% network_plot(min_cor=.1)
```
???
```{r }
corrplot.mixed(cor(bands3.quant), order="hclust", tl.col="black")
```
???
```{r }
ggcorrplot(cor(bands3.quant), p.mat=cor_pmat(bands3[,quanti]), hc.order=TRUE, type='lower')
```
???

## 2.2 Inspected library

```{r }
x<-inspect_types(bands3[,-39])
show_plot(x, col_palette=2)
x<-inspect_na(bands3[,-39])
show_plot(x, col_palette=5)
x<-inspect_num(bands3[,-39])
show_plot(x, col_palette=3)
x<-inspect_cat(bands3[,-39]) 
show_plot(x)
x<-inspect_cor(bands3[,-39])
show_plot(x, col_palette=4)
```

## 2.3 Outliers
 







