---
title: "Intro"
author: "Nina"
date: "05/05/2022"
output: html_document
---

Armance Larfeuille and Nina Bidet  
Teacher : J.Zuber

Semester Spring 2022


### Introduction

*Context*

- Explanation of the printing process : First, an engraved copper cylinder is rotated in a bath of ink. The excess ink is removed and the paper is pressed against the inked image. Then, the engraved image is removed from the cylinder once the job is complete. Finally, the cylinder in re-used.

- Problematic : Presence of grooves in the cylinders that prevent the printing process from working properly. 

- Our goal : Identify anomalies during the printing process in order to reduce or eliminate these banding defects. 


## Report organization

* __Business understanding__
This work is part of the framework of the "Data Analytics for Decision Making" course. We will work on this project by performing a detailed analysis of the 'bands3' database using the CRISP - DM method.
Our goal is to answer our customer's questions about the presence of grooves in the cylinder at some point during the printing process that ruining his products. Thus we will be able to give him solutions to increase the efficiency and quality of his business.
For the rest of the project, the observation "band" will refer to the presence of these grooves, and "noband" will correspond to the absence of those, thus to the good functioning of the cylinder.
By identifying anomalies, we will direct our advices and indications according to these main axes. 

 + What are the variables/parts of the printing process that influence the presence of bands ?
 + How can we modulate these variables to obtain a combination that optimizes the process?

* __Data understanding__ : In this study, we will use the `bands3.csv` database. We will analyse the available variables and correct possible errors. So we will look at the type, number and distribution of each variable and observation and deal with the many missing values so that they do not bias the analysis. 

* __Data preparation__ : Using the exploratory data analysis (EDA), our goal will be to have an exploitable, consistent and homogeneous data base for the analysis of the models. We will then explore this data to find patterns that may explain the presence of grooves. We will also perform some operations that will allow us to have some clues about the origin of the problem. So in this section we will already have a small overview of the most influential variables.

* __Modeling__ : For this part, we will try different models learned during the course. For each of them we will try different tuning parameters and calculate the accuracy. 

* __Evaluation__ : The results obtained in the previous section will allow us to choose the most explanatory models depending on the accuracy and its ability to describe the pattern well. We will give the reasons for this as well as the implications for the future.

* __Conclusion and recommendations__ : Finally, we will think about how to use our results in order to give the best advises to our clients concerning their banding problems and how they can reduce them.
